### ISSUE TITLE
Code Review - Rohan

### ISSUE THREAD

**Issue by Rohanjadeja** [leonjia0112/ec601_passenger_screening#17]
Hi,

Most codes are easily readable and well commented in each individual branch. The master branch contains most of the final codes so that helped.

Most of my concerns about data sources and the images you used for training you model but since it is a kaggle projects and this point was already taken up in class I think I'll just have to read up about it on kaggle.

The training model seems to be giving good results with over 90% of hit accuracy. It'd be great if you guys could mention you dataset size used with the training and testing fractions for the same.
I'd love to a description of how each code segment is put together as well, but it seems like you guys have done a great job at it! Cheers!

**Comment by gvikram31** [comment]
Hello Rohan,

Thanks a lot for the feedback. 

--
Vikram
