### ISSUE TITLE
Code Review of Chenyu Wang

### ISSUE THREAD

**Issue by ChenyuWang123** [leonjia0112/ec601_passenger_screening#3]
## Datadownload.py

The code is clear. The comments helps a lot and the description in the 'for' loop makes it more easier to understand.

## Preprocess.py
  
I noticed there exist some Commented-Out Codes. I wonder what they are for ?

No magic number was used in the script. For instance, in the line 37-39, coders have given the reasonable name to the variables they used and clarified the source of the values. That makes me feel comfortable.

Also whitespace in the code，for instance, the use of consistent indentation makes the code seems more organized.

While in the definition of the function, you have printed some results. I think it would be a better idea to return them rather than print them? In general, only the highest-level parts of a program should interact with the human user or the console. Lower-level parts should take their input as parameters and return their output as results.

## Trainsample.py

Between the line 29 and 65, valid comments were made to clarify the significance of the variables. It is pretty user friendly.

Also the coders have exhibited the output of the codes，that makes me have a better understanding of plans

There exist some global variables , for instance in line 109. I am not sure whether same functions can be implemented in another way. But I think it may be more safe to change global variables into parameters and return values, or put them inside objects that you’re calling methods on. 

Also, it may be more readable if you could add some explanations line 225 and line 249?  

## Summary

In brief, the codes are ready to change, easy to understand and kind of safe from bugs. It introduces me to what they are doing which is really attractive. And the standard they followed in writing codes enlightens. I have learnt useful things from this code review.

**Comment by gvikram31** [comment]
Dear Wang,
Thank you so much for the feedback. I updated the code little bit more so that it is easier to understand. 
We will put final version soon and hopefully, the code will be clean and easy to understand.

Thank you for the response. I really appreciate you taking the time to write the feedback.
