### ISSUE TITLE
Code Review of Shruthi Sivasubramanian

### ISSUE THREAD

**Issue by ShruthiSiva** [leonjia0112/ec601_passenger_screening#5]
I really love your project idea!

The main readme file describes effectively, the data you will be working with, details the various categories that you have divided your project into, as well as gives us an idea of why you chose a particular approach over another, thereby educating us about the various possible solutions to your proposal.

**# datadownload.py**
The code is clear and simple to understand and the comments were very helpful. The variable names are also quite descriptive which is another plus point.

**# preprocess.py**
The variable names are descriptive. I was able to get a gist of the first part of your program because of this. I also like how you've described the function within the program. I do however wonder why you've commented out Options 1 and 3?

**# trainsample.py**
The description given for each variable at the start of your code is very helpful.  I do have a suggestion about the global variables you have used. I think it would be safer for you declare them within the function to avoid clashing of values. 

In the FrontEndWebDev branch, it would be helpful to the readers if the WebApp Page2 file could contain more comments explaining what the structure of the page would look like.
I would recommend the same with draw_rectangle.py and  read_img.py,  in the peijia branch as it's slightly difficult to interpret it without the comments. 

I also think it would be more reader friendly if you describe what exactly it is that you've updated for each commit you've made? 

Overall, I think you guys are doing some great work on a very interesting topic and am sure you'll do a wonderful job at it!

**Comment by gvikram31** [comment]
Hi Shruthi,

Thanks a lot for the feedback. We commented some codes as they supposed to run on BU cluster. We had some library conflicts on BU SCC so added extra unused codes.
