### ISSUE TITLE
Code Review 2 of Chenyu Wang

### ISSUE THREAD

**Issue by ChenyuWang123** [leonjia0112/ec601_passenger_screening#8]
# Summary

Overall, the team has added amounts of contents since the last review. I could see the results.txt, it seems that they have gone through some milestones and reaching their destination. I am really appreciated to have chance to learn from your project. I really like your guys' work and think it remains practical significance. Since I am not an expert in the screening area. I would like to offer some advice for the code. 

## VGGNet.py

I have found some comas are joined with other variables without a space. 

It would be more clear if you could add some function docstring when you define your function.

The import in line 14 26 and 28 is not necessary?
  
In the line 34, there should be 4 space( just like what you did in the following definition of the function.)

Variables between line 101 and line 103 have attributions of global. They may be not safe in some conditions. Maybe it would be better if you can change them to private class?

The line 110 is a bit long, maybe it would be better if you could split it up.

I noticed that contents between line 321 and 341 are commented. I wonder what they are for and why they were left there lonely.

In the line 343 and 344, names of variables could be changed to some meaningful names I think? And name in line 359 is an invalid constant name. It should be replaced by some upper letter?

## preprocessor_one_image.py

There are some lines which are too long in this documents. Maybe they should be split up.

Also the import in line 6 7 8 11 12 are not used. They should be wiped out I think.

The comments between lines and lines help me quickly understand what the code is doing. I would like to say that comments are useful and meaningful

**Comment by gvikram31** [comment]
Hello Chenyu Wang,

Thanks for the feedback. In VGGNet.py, as you pointed out we commented some of the lines and didn't use a few imported libraries. Actually, our code was supposed to run on BU cluster which has libraries conflicts so we made the code in such way that it works for both BU SCC and local PC also. Very soon we will put separate files for BU SCC runnable code and PC runnable code.

Thanks again for your feedback.

--Vikram
