### ISSUE TITLE
Code review 2 of Shengye Li

### ISSUE THREAD

**Issue by ShengyeLi** [leonjia0112/ec601_passenger_screening#9]
All the comments in this review are based on the instruction in 
http://web.mit.edu/6.005/www/fa15/classes/04-code-review/

train_All.py
This work is extremely readable! They make explanations for nearly every functions, variables they use. Their comment includes the meaning for parameters, expected return value and even the possible scope of each variables. For another thing, they pay attention to fabric explicit name for their variables, so that we can imply the meaning and purpose of variables, and understand context much better. In a word, their code are very easy to understand.  

As for their python style, I try to use two style checking tools, pylint and pep8 to go through. As a result, they have done a really nice job in keep their code in a uniform and regular style. This can be well shown by many details. Their make no ambiguous in constants and variables by using all upper-case letter in variables and all lower-case letter in variables. They leave blank at necessary place such as the bit after comma.  

However, there are still something for them to improve.

Since they have used a lot of functions from external libraries, it's a little hard for someone that is not vary familiar with to understand the purpose of those operation involving external functions. So maybe they can leave some comment there.

The second thing is they defined some redundant variables that they never use. For instance, a variable named TRAIN_SET_FILE_LIST.  

Thirdly, it seems that they have tested their code on the one in master brunch. After testing, however, they don't delete the code for testing, which leads to another redundancy. For instance, they import timer for testing, and this library stays without using in the final functional code

I think this little drawbacks pale when compared to what you have done. Congratulation to you guys!

**Comment by gvikram31** [comment]
Hi Shengye,

Thank you so much taking your time to write a detailed feedback.
We will make the code more simple and commented so it is easy to understand.

--Vikram
